### ISSUE TITLE
homey 08.35

### ISSUE THREAD

**Issue by posthok** [jordenc/com.synology.surveillance#1]
many chrashes in 8.35

**Comment by jordenc** [comment]
Give your Synology a fixed IP-address, that might fix a lot. Also, you might have to add your devices again because the latest versions of the Synology app use a different scheme which is not compatible with the older versions. So just delete and re-add your devices.

I see some reports coming in about crashes, but all of them are related to 'no  settings' (old version) or 'not found' (invalid IP address, or IP of the synology changed)

**Comment by posthok** [comment]
My Synology has a fixed ip, in fact all my devices are fixed

**Comment by posthok** [comment]
Could'nt be firmware related? In 8.34 I had No trouble with the app

**Comment by jordenc** [comment]
I just released a new version that has some bugfixes, might help. Not published in the app store yet.

**Comment by posthok** [comment]
It's working ok now, but i have problem sending a snapshot to two persons.

**Comment by jordenc** [comment]
Do you use 2 cards in the 'then' column? (one per person)

You could try to run the app using the developer tools (https://developers.athom.com) and see what the output is when you use the snapshot function.
It is actually quite a 'heavy' function to use so it might be that there are problems when you run that twice shortly after eachother.

PS: The update is published in the app store now.

**Comment by posthok** [comment]
Yes two cards in a flow, maybe i can set the timer to send the snapshot a little bit later.
