### ISSUE TITLE
Variables are not available

### ISSUE THREAD

**Issue by Tweaqer** [jordenc/com.synology.surveillance#2]
Hi, could you make the variables available for this app? Would be great if I could send the picture as a variable to the app for instance. Love the app btw :)
Cheers!

**Comment by jordenc** [comment]
Thanks!

I could make it available but it's not so easy to use the picture data. It needs special handling because of the format. It took me quite some time to convert the Telegram app so it could show the picture correctly; same will have to happen for every app that you want to send the picture to.

So I don't know if it is worth the trouble? Which app would you like to use it with?

**Comment by Tweaqer** [comment]
I would most like to use it with Pushover but it would be also nice if it would work with the Homey app itself. I use them both on Android. Now I receive an email but that's not ideal and it would be a lot better if it could be managed over Pushover for instance :) 👍

**Comment by jordenc** [comment]
I don't use pushover, but I made it work with Telegram =>  https://github.com/jordenc/org.telegram.api.bot
I think the Pushover app will have to be changed in order to make this work, but I'll start with creating the function in this app.

**Comment by Tweaqer** [comment]
Awsome, meanwhile I will start a telegram bot then :)

**Comment by irritanterik** [comment]
pushover does not support images in notifications.

Op 2 jan. 2017 18:32 schreef "Tweaqer" <notifications@github.com>:

**Comment by Tweaqer** [comment]
Thanks for clearing that up @irritanterik what about push notes from the Homey app itself then?

**Comment by irritanterik** [comment]
Well, with pushover you can send an URL with a notification. So maybe some sort of deeplink to an image from your Homey is possible. 
The possibllities of the Homey notifications are (very) limited at the moment. You can't read long messages and there is no archive available within the app.

**Comment by Tweaqer** [comment]
I guess Telegram would be a good alternative as well but how do I make it send the picture from surveilancestation to the Telegram bot? I dont see that option yet?
(and yes, I did setup the bot in the settings menu :) )

**Comment by jordenc** [comment]
It currently only works if you have both apps installed, the Telegram bot connected and then send "/snap" to the bot.
The other way around still has to be made.

**Comment by Tweaqer** [comment]
looking forward to it! :)

**Comment by Tweaqer** [comment]
Hi @jordenc do you have any update on this item? Cheers 👍

**Comment by marcschut002** [comment]
Pushover support images sinds 0.0.9 (beta) . Could you make snapshots compatible with the new release?

**Comment by marcschut002** [comment]
And with Slack? I think this could be the same effort.

**Comment by jordenc** [comment]
I need to start on rebuilding this app to SDKv2 soon, to be able to support the image tokens. I have planned to start on it after rebuilding the Nuki app, since this app is one of the biggest I have made it will take some time.

**Comment by jordenc** [comment]
SDK v2 version is almost ready. I will just wait for 2 icons to be updated before I publish it to the appstore.

Meanwhile, the new app version  is online on Github ... would love to hear if everything works fine if anybody wants to test by installing as a developer, before I publish this new version.

It should recognize your device(s) from older versions. I removed the "snapshot & mail" -functionality since it now supports Homey image tokens which you can use with other apps (like the email-sender and Telegram).
