### ISSUE TITLE
camera started/stopped recording not working as trigger

### ISSUE THREAD

**Issue by paloss** [jordenc/com.synology.surveillance#4]
When making a flow where the recording status is the trigger the system fails. When used in the and/or fields the camera status is correctly noticed. The polling on the settings page is enabled

**Comment by marcschut002** [comment]
Same issue here. Trigger for 'start recording' doesn't work. Any idea how to debug this?

**Comment by marcschut002** [comment]
When I create a flow that triggers itself every 10 sec. and then check if my cam is recording I do get the correct response. The polling option in the settings is probably the issue. I have 2 cams, does the automatic polling setting support that?

**Comment by hplos** [comment]
Not sure if this will ever work. This app checks the resStatus, I think it only gets the settings from the cam. Not if it is actualy recording

I'm trying to get a trigger for motion detection. The recStatus api is like this:

recStatus <integer> Camera recording status.
0: None recording schedule
1: Continue recording schedule
2: Motion detect recording schedule
3: Digital input recording schedule
4: Digital input recording schedule
5: Manual recording schedule
6: External
7: Analytics

**Comment by marcschut002** [comment]
The motion detection with the app does not work or is completely overloading the nas and the homey (logins/connections every x sec.).
 
The best thing to do right now is to let Synology trigger an event by adding an action in SurveillanceStation for your camera that pushes data to the homey. 
The ability to create a trigger in SurveillanceStation is already there and you can create a homey url via the "HTTP request flowkaarten" app https://apps.athom.com/app/com.internet . 

This method is best for both systems because you don't have to pull for information, it gets pushed. 
Maybe this app can implement this method?

**Comment by jordenc** [comment]
Sorry for my late reply guys.

I am working on a new SDK v2 version of this app. I just tested the polling function, didn't really make any chances in it. I added triggers on "starts recording" and "stops recording" and they are correctly detected by the polling function.

Ofcourse, this means it could have a delay of up to 15 seconds.

The thing that @marcschut002 is telling is probably a more secure and faster way to implement triggers on motion detection and such. You can use the Webhooks app at https://apps.athom.com/app/webhook.manager to make this work.
